// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using smartmetercms.Data;

#nullable disable

namespace smartmetercms.Migrations
{
    [DbContext(typeof(smartmetercmsContext))]
    [Migration("20250112223352_AddNewModels2")]
    partial class AddNewModels2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("smartmetercms.Models.Bill", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountDue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BillingPeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BillingPeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("MeterID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PaidStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalEnergyUsed")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.ToTable("Bill");
                });

            modelBuilder.Entity("smartmetercms.Models.EnergyUsage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Current")
                        .HasColumnType("REAL");

                    b.Property<double>("EnergyUsed")
                        .HasColumnType("REAL");

                    b.Property<string>("MeterID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("Voltage")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.ToTable("EnergyUsage");
                });

            modelBuilder.Entity("smartmetercms.Models.IntervalEnergyUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("EnergyUsed")
                        .HasColumnType("REAL");

                    b.Property<string>("MeterID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("IntervalEnergyUsage");
                });

            modelBuilder.Entity("smartmetercms.Models.Payments", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("TEXT");

                    b.Property<int>("BillID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("smartmetercms.Models.User", b =>
                {
                    b.Property<string>("MeterID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.HasKey("MeterID");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
